/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author aldia
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    Color DefaultColor,ClickedColor;
            
    public Dashboard() {
        initComponents();
        
        DefaultColor = new Color (2,153,167);
        ClickedColor = new Color (255,255,255);
        
        MenuDataBarang.setBackground(DefaultColor);
        MenuDataCustomer.setBackground(DefaultColor);
        MenuDataPesanan.setBackground(DefaultColor);
        jLabel1.setForeground(ClickedColor);
        jLabel2.setForeground(ClickedColor);
        Jlabel3.setForeground(ClickedColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuDataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuDataCustomer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuDataPesanan = new javax.swing.JPanel();
        Jlabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 153, 167));

        MenuDataBarang.setBackground(new java.awt.Color(2, 153, 167));
        MenuDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDataBarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuDataBarangMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Barang");

        javax.swing.GroupLayout MenuDataBarangLayout = new javax.swing.GroupLayout(MenuDataBarang);
        MenuDataBarang.setLayout(MenuDataBarangLayout);
        MenuDataBarangLayout.setHorizontalGroup(
            MenuDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDataBarangLayout.setVerticalGroup(
            MenuDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDataBarangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuDataCustomer.setBackground(new java.awt.Color(2, 153, 167));
        MenuDataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDataCustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuDataCustomerMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Customer");

        javax.swing.GroupLayout MenuDataCustomerLayout = new javax.swing.GroupLayout(MenuDataCustomer);
        MenuDataCustomer.setLayout(MenuDataCustomerLayout);
        MenuDataCustomerLayout.setHorizontalGroup(
            MenuDataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDataCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        MenuDataCustomerLayout.setVerticalGroup(
            MenuDataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        MenuDataPesanan.setBackground(new java.awt.Color(2, 153, 167));
        MenuDataPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDataPesananMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuDataPesananMousePressed(evt);
            }
        });

        Jlabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Jlabel3.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel3.setText("Data Pesanan");
        Jlabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuDataPesananLayout = new javax.swing.GroupLayout(MenuDataPesanan);
        MenuDataPesanan.setLayout(MenuDataPesananLayout);
        MenuDataPesananLayout.setHorizontalGroup(
            MenuDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDataPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDataPesananLayout.setVerticalGroup(
            MenuDataPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/store.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuDataCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuDataPesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDataPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelViewLayout = new javax.swing.GroupLayout(PanelView);
        PanelView.setLayout(PanelViewLayout);
        PanelViewLayout.setHorizontalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        PanelViewLayout.setVerticalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDataBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataBarangMousePressed
        // TODO add your handling code here:
        MenuDataBarang.setBackground(ClickedColor);
        MenuDataCustomer.setBackground(DefaultColor);
        MenuDataPesanan.setBackground(DefaultColor);
        jLabel1.setForeground(DefaultColor);
        jLabel2.setForeground(ClickedColor);
        Jlabel3.setForeground(ClickedColor);
    }//GEN-LAST:event_MenuDataBarangMousePressed

    private void MenuDataCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataCustomerMousePressed
        // TODO add your handling code here:
        MenuDataBarang.setBackground(DefaultColor);
        MenuDataCustomer.setBackground(ClickedColor);
        MenuDataPesanan.setBackground(DefaultColor);
        jLabel1.setForeground(ClickedColor);
        jLabel2.setForeground(DefaultColor);
        Jlabel3.setForeground(ClickedColor);
    }//GEN-LAST:event_MenuDataCustomerMousePressed

    private void MenuDataPesananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataPesananMousePressed
        // TODO add your handling code here:
        MenuDataBarang.setBackground(DefaultColor);
        MenuDataCustomer.setBackground(DefaultColor);
        MenuDataPesanan.setBackground(ClickedColor);
        jLabel1.setForeground(ClickedColor);
        jLabel2.setForeground(ClickedColor);
        Jlabel3.setForeground(DefaultColor);
    }//GEN-LAST:event_MenuDataPesananMousePressed

    private void MenuDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataBarangMouseClicked
        // TODO add your handling code here:
        FormBarang menu = new FormBarang();
        PanelView.removeAll();
        PanelView.add(menu).setVisible(true);
    }//GEN-LAST:event_MenuDataBarangMouseClicked

    private void Jlabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Jlabel3MouseClicked

    private void MenuDataPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataPesananMouseClicked
        // TODO add your handling code here:
        FormPemesanan menu = new FormPemesanan();
        PanelView.removeAll();
        PanelView.add(menu).setVisible(true);
    }//GEN-LAST:event_MenuDataPesananMouseClicked

    private void MenuDataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataCustomerMouseClicked
        // TODO add your handling code here:
        FormCustomer menu = new FormCustomer();
        PanelView.removeAll();
        PanelView.add(menu).setVisible(true);
    }//GEN-LAST:event_MenuDataCustomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JPanel MenuDataBarang;
    private javax.swing.JPanel MenuDataCustomer;
    private javax.swing.JPanel MenuDataPesanan;
    private javax.swing.JPanel PanelView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

            
}
